services:
  mysql:
    image: mysql:8-oracle
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password        # 필수. MySQL의 root 사용자의 비밀번호
      MYSQL_USER: intern                   # 새로 생성할 사용자 이름
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: work
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - intern-network
volumes:
  mysql-data:
  redis-data:

networks:
  intern-network:
    driver: bridge